# Using circleCI 2
version: 2

jobs:
  build:
    working_directory: ~/ilorm
    docker:
      - image: circleci/mongo:latest
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: "Update npm version"
          command: sudo npm install -g npm@latest
      - run:
          name: "Run npm install"
          command: npm install
      - run:
          name: test
          command: npm run circle_ci_test

